// AvatarScript library: avatar + script → speech, timed score and video.
export { parseScript, plainScript, ScriptError, EMOTIONS } from "./script.ts";
export type { Script, Segment, Cue, Emotion } from "./script.ts";
export { loadAvatar, AvatarManifestSchema } from "./avatar.ts";
export type { Avatar, AvatarManifest } from "./avatar.ts";
export { compile, detectLang } from "./compile.ts";
export type { CompileOptions } from "./compile.ts";
export { render } from "./render.ts";
export type { RenderOptions } from "./render.ts";
export { ScoreSchema, ScoreCueSchema } from "./score.ts";
export type { Score, ScoreCue } from "./score.ts";
export { createTts, isTtsProvider, TTS_PROVIDERS, TtsConfigSchema, SPEECH_SAMPLE_RATE } from "./tts/index.ts";
export type { TtsConfig, TtsProvider, TextToSpeech, Speech, SpeechRequest } from "./tts/index.ts";
export { refineTiming } from "./timing.ts";
export { textVisemes } from "./g2p/index.ts";
export type { CharTime } from "./g2p/types.ts";
export { VISEMES } from "./visemes.ts";
export type { Viseme, VisemeEvent } from "./visemes.ts";
export { toWav, fromWav } from "./audio.ts";
export type { Pcm } from "./audio.ts";
